# 1. Make release PR from main branch
# 2. Publish if release is created by release-please
# https://github.com/google-github-actions/release-please-action

name: release-please

on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          config-file: .release-please-config.json

      - name: release created
        run: echo "release created:" ${{ steps.release.outputs.release_created }}