# 1. Make release PR from main branch
# 2. Publish if release is created by release-please
# https://github.com/google-github-actions/release-please-action

name: release-please

on:
  push:
    branches:
      - release
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Debug release output
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Release type: ${{ steps.release.outputs.release_type }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"

      # The logic below handles the npm publication:
      - name: Set up Node.js
        if: steps.release.outputs.release_created == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Create .npmrc
        if: steps.release.outputs.release_created == 'true'
        run: mv .npmrc.forgithubaction .npmrc

      - name: Install dependencies
        if: steps.release.outputs.release_created == 'true'
        run: yarn install --frozen-lockfile

      - name: Build package
        if: steps.release.outputs.release_created == 'true'
        run: yarn build

      - name: Publish to npm
        if: steps.release.outputs.release_created == 'true'
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}