# 1. Make release PR from main branch
# 2. Publish if release is created by release-please
# https://github.com/google-github-actions/release-please-action

name: release-please

on:
  push:
    branches:
      - release
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: release created
        run: echo "release created:" ${{ steps.release.outputs.release_created }}

        # The logic below handles the npm publication:
      - name: Set up Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
      - name: Create .npmrc
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - if: ${{ steps.release.outputs.release_created }}
        run: mv .npmrc.forgithubaction .npmrc
      - if: ${{ steps.release.outputs.release_created }}
        run: yarn                    
      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}